
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "ID INT PP PRECOLC : LC CatLC : CatCat : ID ':' ProdsProds : Prods ProdutoProds : Produto : '-' INT PP ID PP PRECO PP INT ';'"
    
_lr_action_items = {'ID':([0,1,2,4,5,6,7,10,16,],[3,3,-2,-1,-5,-3,-4,11,-6,]),'$end':([1,2,4,5,6,7,16,],[0,-2,-1,-5,-3,-4,-6,]),':':([3,],[5,]),'-':([5,6,7,16,],[-5,8,-4,-6,]),'INT':([8,14,],[9,15,]),'PP':([9,11,13,],[10,12,14,]),'PRECO':([12,],[13,]),';':([15,],[16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'LC':([0,],[1,]),'Cat':([0,1,],[2,4,]),'Prods':([5,],[6,]),'Produto':([6,],[7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> LC","S'",1,None,None,None),
  ('LC -> LC Cat','LC',2,'p_LC1','dsadsad.py',83),
  ('LC -> Cat','LC',1,'p_LC2','dsadsad.py',84),
  ('Cat -> ID : Prods','Cat',3,'p_Cat','dsadsad.py',86),
  ('Prods -> Prods Produto','Prods',2,'p_Prods1','dsadsad.py',88),
  ('Prods -> <empty>','Prods',0,'p_Prods2','dsadsad.py',89),
  ('Produto -> - INT PP ID PP PRECO PP INT ;','Produto',9,'p_Produto','dsadsad.py',91),
]
